USE ROLE ACCOUNTADMIN;
USE DATABASE AIRLINE_DB;
-- 1. ПРОВЕРКА ЛОГОВ (Audit Log)

SELECT * FROM AIRLINE_DB.AUDIT_DATA.ETL_LOGS
ORDER BY created_at DESC
LIMIT 10;

-- 2. ПРОВЕРКА SILVER СЛОЯ
-- Проверяем, что данные очистились и загрузились.
SELECT * FROM AIRLINE_DB.SILVER_DATA.FLIGHTS_SILVER
LIMIT 10;

-- Считаем общее количество загруженных строк
SELECT COUNT(*) as TOTAL_ROWS_SILVER
FROM AIRLINE_DB.SILVER_DATA.FLIGHTS_SILVER;

-- 3. ПРОВЕРКА GOLD СЛОЯ
SELECT * FROM AIRLINE_DB.GOLD_DATA.DAILY_AIRPORT_STATS
ORDER BY stat_date DESC, total_flights DESC
LIMIT 10;

-- 4. ПРОВЕРКА БЕЗОПАСНОСТИ (Secure View)
SELECT * FROM AIRLINE_DB.GOLD_DATA.FLIGHTS_SECURE_REPORT
LIMIT 10;

-- 5. ПРОВЕРКА СТРИМОВ (Streams)

-- Стрим 1: Raw -> Silver
SELECT SYSTEM$STREAM_HAS_DATA('AIRLINE_DB.RAW_DATA.FLIGHTS_STREAM_ON_RAW') as RAW_STREAM_HAS_DATA;

-- Стрим 2: Silver -> Gold
SELECT SYSTEM$STREAM_HAS_DATA('AIRLINE_DB.SILVER_DATA.FLIGHTS_SILVER_STREAM') as SILVER_STREAM_HAS_DATA;