USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE AIRLINE_DB;
USE SCHEMA SILVER_DATA;

SELECT COUNT(*) FROM FLIGHTS_SILVER;

DELETE FROM FLIGHTS_SILVER WHERE country_name = 'France';

SELECT COUNT(*) FROM FLIGHTS_SILVER;

SELECT count(*) FROM FLIGHTS_SILVER AT(OFFSET => -120);

INSERT INTO FLIGHTS_SILVER
SELECT * FROM FLIGHTS_SILVER AT(OFFSET => -120)
WHERE country_name = 'France';
SELECT COUNT(*) FROM FLIGHTS_SILVER;


CREATE OR REPLACE TABLE FLIGHTS_SILVER_BACKUP
CLONE FLIGHTS_SILVER;


DROP TABLE FLIGHTS_SILVER_BACKUP;

UNDROP TABLE FLIGHTS_SILVER_BACKUP;

SELECT COUNT(*) FROM FLIGHTS_SILVER_BACKUP;